In [ ]:
import numpy as np

In [ ]:
arr = np.array([
    [1,2,3],
    [5,6,7]
])

In [ ]:
arr.shape

(2, 3)

In [ ]:
arr.ndim

2

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr = np.array([
    [1,2,"data"],
    [5,6,7]
])

In [ ]:
arr.shape

(2, 3)

In [ ]:
arr.dtype

dtype('<U21')

In [ ]:
arr = np.array(["apple","banana","watermelon"])
arr.dtype

dtype('<U10')

#transpose

In [ ]:
#array reshaping
arr = np.array([
    [1,2,3],
    [5,6,7]
])

In [ ]:
# 2*3 = 6 (1,5),(5,1),(2,4),(4,2)
reshaped_2d = arr.reshape(3,2)
reshaped_2d

array([[1, 2],
       [3, 5],
       [6, 7]])

In [ ]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
reshape = arr.reshape(6,2)  #reshape le tuple ma value dincha
reshape

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
reshape.shape

(6, 2)

In [ ]:
flattened = reshape.flatten()
flattened

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
raveled = reshape.ravel()
raveled

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
#array reshaping
arr = np.array([
    [1,2,3],
    [5,6,7]
])

In [ ]:
arr.shape

(2, 3)

In [ ]:
#reanspose

transpose = arr.T
transpose

array([[1, 5],
       [2, 6],
       [3, 7]])

In [ ]:
transpose.shape

(3, 2)

In [ ]:
#numpy array operation

In [ ]:
#indexing and slicing

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[2:7])

[3 4 5 6 7]


In [ ]:
#class task 2D slicing

arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]

])
print(arr[0:1,0:2])

[[1 2]]


In [ ]:
print(arr[1:3,1:4])   #sub matrix

[[5 6]
 [8 9]]


In [ ]:
print(arr[0:2])  #row only

[[1 2 3]
 [4 5 6]]


In [ ]:
print(arr[:,0:2]) # column only

[[1 2]
 [4 5]
 [7 8]]


In [ ]:
print(arr[::-1]) #reverse rows

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [ ]:
print(arr[:,::-1]) #reverse columns

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [ ]:
# sorting

unsorted = np.array([1,2,3,4,5,7,6,0,9])
print(np.sort(unsorted))

[0 1 2 3 4 5 6 7 9]


In [ ]:
#class work sort 2D

arr = np.array([
    [1,4,3],
    [5,2,8],
    [7,6,9]

])
print(np.sort(arr))

[[1 3 4]
 [2 5 8]
 [6 7 9]]


In [ ]:
print(np.sort(arr,axis=1))  #sort by row

[[1 3 4]
 [2 5 8]
 [6 7 9]]


In [ ]:
print(np.sort(arr,axis=0))  #sort by column

[[1 2 3]
 [5 4 8]
 [7 6 9]]


In [ ]:
#filter

numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers%2==0]
print(even_number)

[ 2  4  6  8 10]


In [ ]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
odd_number=numbers[numbers%2!=0]
print(odd_number)

[1 3 5 7 9]


In [ ]:
#filter with mask

mask = numbers > 5
print(numbers[mask])

[ 6  7  8  9 10]


In [ ]:
numbers[numbers>5]=1000
print(numbers)

[   1    2    3    4    5 1000 1000 1000 1000 1000]


In [ ]:
#np.where

where_result = np.where(numbers==5)   #get index position where number is 5
print(where_result)   #inex position
print("number where",numbers[where_result])

(array([4]),)
number where [5]


In [ ]:
import numpy as np
numbers = np.array([2,8,4,10,5,7])
result = np.where(numbers > 5)
print(result)

(array([1, 3, 5]),)


In [ ]:
conditional_array = np.where(numbers > 5 , numbers*4,numbers)
conditional_array

array([ 2, 32,  4, 40,  5, 28])

In [ ]:
#adding data
arr1 = np.array([1,2,3])
arr2 = np.array([5,6,7])
add = arr1 + arr2
add

array([ 6,  8, 10])

In [ ]:
combine = np.concatenate((arr1,arr2))
combine

array([1, 2, 3, 5, 6, 7])

In [ ]:
combine.shape

(6,)

In [ ]:
arr1.shape = arr2.shape #check matrix compatibality

In [ ]:
arr0 =np.array([
    [1,2],
     [3,4]
])
arr1 =np.array([5,6])
combine=np.vstack((arr0,arr1))
combine

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
arr0 =np.array([
    [1,2],
     [3,4]
])
arr1 =np.array([[5],[6]])
combine=np.hstack((arr0,arr1))
combine

array([[1, 2, 5],
       [3, 4, 6]])