In [ ]:
import numpy as np

matrix_1 = np.array([
    [1,2],
    [3,4]
])
matrix_1

array([[1, 2],
       [3, 4]])

In [ ]:
matrix_2 = np.array([
    [4,6],
    [7,8]
])
matrix_2

array([[4, 6],
       [7, 8]])

#element wise matrix addition

In [ ]:


result = matrix_1 + matrix_2
result

array([[ 5,  8],
       [10, 12]])

#element wise matrix subtraction


In [ ]:

matrix_sub = matrix_1 - matrix_2
matrix_sub

array([[-3, -4],
       [-4, -4]])

In [ ]:
# matrix_mult = matrix_1 * matrix_2
# matrix_mult                          wrong concept

array([[ 4, 12],
       [21, 32]])

#matrix multiplication


In [ ]:
result_mux = matrix_1 @ matrix_2
result_mux

array([[18, 22],
       [40, 50]])

In [ ]:
result_mux = np.matmul(matrix_1,matrix_2)
result_mux

array([[18, 22],
       [40, 50]])

In [ ]:
result_div = matrix_1 / matrix_2      #not recommended
result_div

array([[0.25      , 0.33333333],
       [0.42857143, 0.5       ]])

# element wise operations with scalar


In [ ]:

print(matrix_1)
print("///////////")
scalar = 2
result_add = matrix_1 + scalar
print(result_add)

[[1 2]
 [3 4]]
///////////
[[3 4]
 [5 6]]


#boardcasting


In [ ]:

matrix_3 = np.array([
    [1,2],
    [3,4]
])
array_1 = np.array([
    [5,6]
])

result_broad = matrix_3 + array_1
result_broad

array([[ 6,  8],
       [ 8, 10]])

#computing the determinant


In [ ]:

A = np.array([
    [1,2],
    [3,4]
])

det = np.linalg.det(A)
print(det)

-2.0000000000000004


#inverse
#we can compute the inverse of a matrix using the linalg.inv() function.

In [ ]:


a_inv = np.linalg.inv(A)
print(a_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
print(A@a_inv)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [ ]:
#qn

a = np.array([
    [2,1],
    [1,3]
])

b = np.array([5,6])
X = np.linalg.solve(a,b)
X

array([1.8, 1.4])

In [ ]:
#class task

# x+y+z=6
# 2x+5y+z=-4
# 2x+3y+8z=5


a = np.array([
    [1,1,1],
    [2,5,1],
    [2,3,8]
])

b = np.array([6,-4,5])
X = np.linalg.solve(a,b)
X

array([11.68421053, -5.42105263, -0.26315789])

In [ ]:
a=np.array([
    [1,1],
    [2,1],
    [3,1]
])
b=np.array([2,3,5])

beta=np.linalg.inv(a.T@a)@a.T@b
beta

array([1.5       , 0.33333333])

In [ ]:
print("slope(m)",beta[0])
print("intercept(c)",beta[1])

slope(m) 1.499999999999999
intercept(c) 0.3333333333333348
