In [1]:
import numpy as np

In [2]:
#1D numpy

arr_1D = np.array([1,2,3,4,5])
print(arr_1D)

[1 2 3 4 5]


In [3]:
#1D numpy

arr_1D = np.array([1,2,3,4,5.5])
print(arr_1D)

[1.  2.  3.  4.  5.5]


In [4]:
#2D numpy

arr_2D = np.array([[1,2,3,4,5],[9,8,7,6,5]])
print(arr_2D)

[[1 2 3 4 5]
 [9 8 7 6 5]]


In [5]:
#3D numpy (nested array)

arr_3D = np.array([[[1,2,3,4,5],[9,8,7,6,5]],[[1,4,7,5,8],[1,5,9,7,8]]])
print(arr_3D)

[[[1 2 3 4 5]
  [9 8 7 6 5]]

 [[1 4 7 5 8]
  [1 5 9 7 8]]]


In [6]:
arr_3D.shape

(2, 2, 5)

#qn - list vs numpy array

In [7]:
#list

import time
start = time.time()
py_list = [i*2 for i in range(100000000)]
print("\n list operation time:",time.time()-start)


 list operation time: 9.898442506790161


In [8]:
#numpy

start = time.time()
np_array = np.arange(100000000)*2
print("\n Numpy operation time:",time.time()-start)


 Numpy operation time: 0.2964498996734619


In [9]:
#list

py_list = [1,2,3]
print("python list multiplication",py_list*3)

python list multiplication [1, 2, 3, 1, 2, 3, 1, 2, 3]


In [10]:
#numpy

ny_array = np.array([1,2,3])                    #element wise multiplication
print("numpy array multiplication",ny_array*3)  # 3 is called scalar,we can perform the vector multiplication


numpy array multiplication [3 6 9]


In [24]:
# rank 0 (scalar)

a = np.array(10)
a.ndim

0

In [25]:
a.shape

()

In [22]:
#rank 1 (vector)

a1 = np.array([1,2,3,4])
a1.ndim

1

In [23]:
a1.shape

(4,)

In [20]:
#rank 2 (matrix)

a2 = np.array([
    [1,2,3],
    [4,5,6]
])
a2.ndim

2

In [21]:
a2.shape

(2, 3)

In [26]:
#class work

# create the 5*5 matrix and see the rank
#rank,shape,ndim,create array

a3 = np.array([
    [1,2,3,4,5],
    [1,2,3,4,5],
    [1,2,3,4,5],
    [1,2,3,4,5],
    [1,2,3,4,5]
])
a3.ndim

2

In [27]:
a3.shape

(5, 5)

In [30]:
zeros = np.zeros((5,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [35]:
ones = np.ones((5,5), dtype="int")
ones

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [36]:
np.ones(shape=(4,5),dtype="int8")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [38]:
a = np.array([
    [1,2,4],
    [4,3,5]
])
print(a.sum(axis=0))  #0=column

[5 5 9]


In [41]:
print(a.sum(axis=1))  #1 = row

[ 7 12]


In [42]:
#random array

random = np.random.random((5,5))
random

array([[0.51205117, 0.24663071, 0.3070045 , 0.01161125, 0.53144224],
       [0.09087735, 0.59498361, 0.51452553, 0.05705401, 0.13044771],
       [0.89833402, 0.07004391, 0.86809577, 0.39990124, 0.51629517],
       [0.63750553, 0.48679383, 0.02010392, 0.32054892, 0.55235506],
       [0.95005448, 0.65057352, 0.33960855, 0.23732059, 0.46151726]])

In [43]:
#full

full = np.full((5,2,4),9)
full

array([[[9, 9, 9, 9],
        [9, 9, 9, 9]],

       [[9, 9, 9, 9],
        [9, 9, 9, 9]],

       [[9, 9, 9, 9],
        [9, 9, 9, 9]],

       [[9, 9, 9, 9],
        [9, 9, 9, 9]],

       [[9, 9, 9, 9],
        [9, 9, 9, 9]]])

In [44]:
#linespace() - create evenly spaced value

arr = np.linspace(0,100,20)
arr

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

In [45]:
#diag() - creates diagonal matrix

arr = np.diag([1,2,3,4])
arr

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [51]:
#eye = create matrix with ones on diagonal

arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
arr = np.eye(5,6)
arr

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [50]:
# identity () - create identity matrix(always squre matirx)

arr = np.identity(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [54]:
#create array of random numbers
arr = np.random.rand(2,3)
arr

array([[0.5375449 , 0.23207243, 0.39139235],
       [0.45951673, 0.15149629, 0.17500646]])

In [56]:
#arange
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
arr = np.arange(3,8)   # start=3 and stop=8
arr

array([3, 4, 5, 6, 7])